#jackson时区
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/yl_reptile?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&nullNamePatternMatchesAll=true
    username: root
    password: 123456
